import { Inter } from "next/font/google";
import "./globals.css";
import ProviderApp from "@/redux/provider";
import UiProvider from "@/lib/uiProvider";
import Layout from "@/components/layout/Layout";
import Tprovider from "@/lib/Tprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200 dark:bg-slate-800`}>
        <ProviderApp>
          <Tprovider>
            <UiProvider>
              <Layout>{children}</Layout>
            </UiProvider>
          </Tprovider>
        </ProviderApp>
      </body>
    </html>
  );
}
