import { Inter } from "next/font/google";
import "../globals.css";
import ProviderApp from "@/redux/provider";
import UiProvider from "@/lib/uiProvider";
import Layout from "@/components/layout/Layout";
import Tprovider from "@/lib/Tprovider";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body className={`${inter.className} bg-slate-200 dark:bg-slate-800`}>
        <NextIntlClientProvider messages={messages}>
          <ProviderApp>
            <Tprovider>
              <UiProvider>
                <Layout>{children}</Layout>
              </UiProvider>
            </Tprovider>
          </ProviderApp>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
